#apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testvm
  labels:
    app: testvm
spec:
  replicas: 3
  selector:
    matchLabels:
      machine: testvm
  template:
    metadata:
      labels:
        machine: testvm
    spec:
      containers:
      - name: machine
        image: docker.io/fabiand/lvm
        command: ["/launch", "testvm"]
        stdin: True
        tty: True
        ports:
        - containerPort: 5942
          protocol: TCP
