apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.kubevirt.io
spec:
  group: kubevirt.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: virtualmachines
    singular: virtualmachine
    kind: VirtualMachine
    shortNames:
    - vm
    - vms
---
apiVersion: v1
kind: Service
metadata:
  name: iscsi-demo-target
spec:
  ports:
    - name: iscsi
      port: 3260
      targetPort: 3260
  selector:
    app: iscsi-demo-target
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iscsi-demo-target-tgtd
spec:
  template:
    metadata:
      labels:
        name: iscsi-demo-target-tgtd
        app: iscsi-demo-target
      name: iscsi-demo-target-tgtd
    spec:
      containers:
        - name: target
          image: kubevirt/iscsi-demo-target-tgtd:v0.0.2
          ports:
            - containerPort: 3260
