apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iscsi-demo-target-tgtd
spec:
  template:
    metadata:
      labels:
        name: iscsi-demo-target-tgtd
        app: iscsi-demo-target
      name: iscsi-demo-target-tgtd
    spec:
      containers:
        - name: target
          image: kubevirt/iscsi-demo-target-tgtd:v0.0.2
          ports:
            - containerPort: 3260
