apiVersion: v1
kind: Pod
metadata:
  name: testvm
  labels:
    machine: testvm
spec:
  containers:
  - name: machine
    image: docker.io/fabiand/lvm
    command: ["/launch"]
    stdin: True
    tty: True
    ports:
    - containerPort: 5942
      protocol: TCP
