apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm
  uuid: 3fe93aa1-a08c-422d-b4c6-c81061e619b0
spec:
  domain:
    devices:
      graphics:
      - type: vnc
      interfaces:
      - type: network
        model:
          type: e1000
        source:
          network: default
      video:
      - type: qxl
      disks:
      - type: network
        snapshot: external
        transient: true
        device: disk
        driver:
          name: qemu
          type: raw
          cache: none
        source:
          # The source is provided by the iSCSI demo target
          # Usually you could use PVs here.
          host:
            name: iscsi-demo-target.default
            port: "3260"
          protocol: iscsi
          name: iqn.2017-01.io.kubevirt:sn.42/2
        target:
          dev: vda
      consoles:
      - type: pty
    memory:
      unit: MB
      value: 64
    os:
      type:
        os: hvm
    type: qemu
